name: aqua_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^6.2.1
  latlong2: ^0.9.1

  #Firebase Core
  firebase_core: ^3.6.0

  #Authentication
  firebase_auth: ^5.3.0

  #Firestore (for water parameters)
  cloud_firestore: ^5.4.0
  url_launcher: ^6.2.5
  firebase_database: ^11.3.10
  firebase_messaging: ^15.1.3

  fl_chart: ^0.68.0
  google_fonts: ^8.0.1

  http: ^1.1.0
  intl: ^0.20.2
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_local_notifications: ^20.1.0
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  uuid: ^4.5.3
  firebase_storage: ^12.4.10
  google_generative_ai: ^0.4.7
  speech_to_text: ^7.3.0
  record: ^6.2.0
  audioplayers: ^6.6.0
  flutter_map_marker_cluster: ^1.3.6
  shared_preferences: ^2.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/maps/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
