import 'dart:html' as html;
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../screens/farm_details_screen.dart';

final List<Map<String, dynamic>> _mockFarms = const [
  {
    "id": "FRM-2024-001",
    "name": "Goa Smart Prawn Farm",
    "owner": "Rajesh Sharma",
    "contact": "+91 98765 43210",
    "email": "rajesh.sharma@example.com",
    "address": "Plot 42, Coastal Road, Calangute",
    "district": "North Goa",
    "taluka": "Bardez",
    "village": "Calangute",
    "totalArea": "2.5 ha",
    "pondCount": 4,
    "regDate": "2023-01-15",
    "license": "LIC-2023-001",
    "status": "Active",
    "lat": 15.5406,
    "lng": 73.7562,
    "geofenceRadius": "500m",
    "soilType": "Clay Loam",
    "landCategory": "Coastal",
    "floodZone": "Moderate Risk",
    "waterSource": "Estuary & Borewell",
    "elevation": "4m",
    "ph": 7.8,
    "temp": 28.5,
    "turbidity": "12 NTU",
    "do": "6.5 mg/L",
    "salinity": "15 ppt",
    "lastUpdate": "10 mins ago",
    "riskStatus": "Normal",
    "alarmCount": 0,
    "species": "Vannamei Shrimp",
    "quantity": "50,000",
    "stockDate": "2023-11-01",
    "harvestDate": "2024-03-15",
    "feedType": "Growel Feeds - Starter",
    "feedSupplier": "Goa Feeds Ltd",
    "growthStage": "Growth Phase",
    "diseaseHistory": "None",
    "diseaseAlerts": "None",
    "floodAlertHistory": "Oct 2023 - Minor",
    "pollutionScore": "Low (12/100)",
    "insuranceClaims": "None",
    "scheme": "PMMSY - Biofloc Support",
    "subsidyStatus": "Approved - 40%",
    "insuranceDetails": "Oriental Insurance - Valid till Dec 2024",
    "revenueEst": "₹ 12,0,000",
    "lossHistory": "Nil",
    "docs": {
      "License": "Verified",
      "Land Ownership": "Verified",
      "Pollution Cert": "Verified",
      "Bank Details": "Verified",
      "ID Proof": "Verified"
    },
    "productivity": "4.2 tons/ha",
    "mortalityRate": "5%",
    "sustainabilityScore": "85/100",
    "inspector": "Dr. V. Naik",
    "inspectionDate": "2023-12-10",
    "remarks": "Excellent adherence to biosecurity protocols.",
    "approvalTime": "2023-12-12 10:00 AM",
  },
  {
    "id": "FRM-2024-002",
    "name": "Khazan Traditional Farm",
    "owner": "Sandeep Naik",
    "contact": "+91 91234 56789",
    "email": "s.naik@example.com",
    "address": "H.No 12, Riverside, Divar Island",
    "district": "North Goa",
    "taluka": "Tiswadi",
    "village": "Divar",
    "totalArea": "5.0 ha",
    "pondCount": 1,
    "regDate": "2024-02-01",
    "license": "Pending",
    "status": "Pending Approval",
    "lat": 15.51,
    "lng": 73.91,
    "geofenceRadius": "1000m",
    "soilType": "Saline Alluvial",
    "landCategory": "Khazan Land",
    "floodZone": "High Risk",
    "waterSource": "River Mandovi",
    "elevation": "1m",
    "ph": 7.2,
    "temp": 29.1,
    "turbidity": "45 NTU (High)",
    "do": "5.1 mg/L",
    "salinity": "22 ppt",
    "lastUpdate": "1 hour ago",
    "riskStatus": "Warning",
    "alarmCount": 2,
    "species": "Local Mullet & Pearl Spot",
    "quantity": "Natural Stocking",
    "stockDate": "N/A",
    "harvestDate": "April 2024",
    "feedType": "Natural Algae",
    "feedSupplier": "N/A",
    "growthStage": "Maturation",
    "diseaseHistory": "Minor Gill Rot in 2022",
    "diseaseAlerts": "Watch for fungal infection",
    "floodAlertHistory": "High Tide Breach - Aug 2023",
    "pollutionScore": "Moderate (45/100)",
    "insuranceClaims": "Claim #4421 - Pending",
    "scheme": "State Khazan Revival",
    "subsidyStatus": "Application Submitted",
    "insuranceDetails": "Not yet insured",
    "revenueEst": "₹ 5,00,000",
    "lossHistory": "₹ 50,000 (Monsoon 2023)",
    "docs": {
      "License": "In Process",
      "Land Ownership": "Verified",
      "Pollution Cert": "Pending",
      "Bank Details": "Verified",
      "ID Proof": "Verified"
    },
    "productivity": "1.5 tons/ha",
    "mortalityRate": "Unknown",
    "sustainabilityScore": "92/100",
    "inspector": "Pending Assignment",
    "inspectionDate": "Scheduled: 2024-02-25",
    "remarks": "Waiting for site visit.",
    "approvalTime": "N/A",
  },
  {
    "id": "FRM-2023-089",
    "name": "Mandovi Cage Culture",
    "owner": "Anthony Fernandes",
    "contact": "+91 98221 55555",
    "email": "a.fernandes@example.com",
    "address": "Jetty Road, Panjim",
    "district": "North Goa",
    "taluka": "Tiswadi",
    "village": "Panjim",
    "totalArea": "10 Cages",
    "pondCount": 10,
    "regDate": "2023-05-10",
    "license": "LIC-CAGE-003",
    "status": "Inactive",
    "lat": 15.5000,
    "lng": 73.8300,
    "geofenceRadius": "200m",
    "soilType": "River Bed",
    "landCategory": "Estuarine",
    "floodZone": "Moderate",
    "waterSource": "River Mandovi",
    "elevation": "0m",
    "ph": "N/A",
    "temp": "N/A",
    "turbidity": "N/A",
    "do": "N/A",
    "salinity": "N/A",
    "lastUpdate": "Offline (30 days)",
    "riskStatus": "Critical",
    "alarmCount": 0,
    "species": "Asian Seabass",
    "quantity": "0",
    "stockDate": "Harvested Dec 2023",
    "harvestDate": "N/A",
    "feedType": "Floating Pellets",
    "feedSupplier": "Cargill",
    "growthStage": "Fallow",
    "diseaseHistory": "None",
    "diseaseAlerts": "None",
    "floodAlertHistory": "None",
    "pollutionScore": "High (Traffic)",
    "insuranceClaims": "None",
    "scheme": "Blue Revolution",
    "subsidyStatus": "Received",
    "insuranceDetails": "Expired Jan 2024",
    "revenueEst": "₹ 0",
    "lossHistory": "Nil",
    "docs": {
      "License": "Expired",
      "NOC": "Valid",
    },
    "productivity": "Total 5 tons (2023)",
    "mortalityRate": "2%",
    "sustainabilityScore": "70/100",
    "inspector": "Dr. V. Naik",
    "inspectionDate": "2023-11-20",
    "remarks": "Operations temporarily suspended.",
    "approvalTime": "2023-05-15",
  },
  {
    "id": "FRM-2024-005",
    "name": "Zuari Biofloc Unit",
    "owner": "Preeti Singh",
    "contact": "+91 77777 88888",
    "email": "p.singh@example.com",
    "address": "Ind. Estate, Cortalim",
    "district": "South Goa",
    "taluka": "Mormugao",
    "village": "Cortalim",
    "totalArea": "0.5 ha",
    "pondCount": 6,
    "regDate": "2024-01-10",
    "license": "Rejected",
    "status": "Rejected",
    "lat": 15.4000,
    "lng": 73.9500,
    "geofenceRadius": "100m",
    "soilType": "Laterite",
    "landCategory": "Industrial",
    "floodZone": "Low",
    "waterSource": "Municipal Supply",
    "elevation": "15m",
    "ph": "-",
    "temp": "-",
    "turbidity": "-",
    "do": "-",
    "salinity": "-",
    "lastUpdate": "Never",
    "riskStatus": "Unknown",
    "alarmCount": 0,
    "species": "Tilapia",
    "quantity": "0",
    "stockDate": "N/A",
    "harvestDate": "N/A",
    "feedType": "N/A",
    "feedSupplier": "N/A",
    "growthStage": "N/A",
    "diseaseHistory": "N/A",
    "diseaseAlerts": "N/A",
    "floodAlertHistory": "N/A",
    "pollutionScore": "High (Ind. Waste)",
    "insuranceClaims": "N/A",
    "scheme": "PMMSY",
    "subsidyStatus": "Rejected",
    "insuranceDetails": "N/A",
    "revenueEst": "0",
    "lossHistory": "N/A",
    "docs": {
      "License": "Rejected",
      "Land Ownership": "Disputed",
      "Pollution Cert": "Pending",
      "Bank Details": "Verified",
      "ID Proof": "Verified"
    },
    "productivity": "N/A",
    "mortalityRate": "N/A",
    "sustainabilityScore": "20/100",
    "inspector": "Official #42",
    "inspectionDate": "2024-01-20",
    "remarks": "Land use mismatch. Industrial zone not improved for aquaculture.",
    "approvalTime": "N/A",
    "rejectionReason": "Land Use Violation",
  }
];

void registerMessageListener(GlobalKey<NavigatorState> navigatorKey) {
  html.window.addEventListener('message', (event) {
    try {
      final data = event is html.MessageEvent ? event.data : null;
      final parsed = (data is String) ? (data.isNotEmpty ? jsonDecode(data) : null) : data;
      if (parsed != null && parsed['type'] == 'openFarm') {
        final id = parsed['id'];
        if (id != null && navigatorKey.currentState != null) {
          // 1. First fallback to local mock farms
          final mockFarm = _mockFarms.firstWhere(
            (f) => f['id'] == id,
            orElse: () => <String, dynamic>{}
          );
          if (mockFarm.isNotEmpty) {
            navigatorKey.currentState!.push(
              MaterialPageRoute(builder: (_) => FarmDetailsScreen(farmData: mockFarm, isAuthority: true))
            );
          } else {
            // 2. Fetch farm data from Firestore
            FirebaseFirestore.instance.collection('farms').doc(id).get().then((doc) {
              if (doc.exists) {
                final farmData = Map<String, dynamic>.from(doc.data() ?? {});
                farmData['id'] = doc.id;
                navigatorKey.currentState!.push(
                  MaterialPageRoute(builder: (_) => FarmDetailsScreen(farmData: farmData, isAuthority: true))
                );
              }
            });
          }
        }
      }
    } catch (e) {
      // ignore
    }
  });
}
