// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _databaseURL =
      'https://aquaapp-1564f-default-rtdb.asia-southeast1.firebasedatabase.app/';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdexqtFzXdLMOAulMB6Lkx3OVHAoSRwF4',
    appId: '1:870482339256:web:93d417eb11020965f71b4d',
    messagingSenderId: '870482339256',
    projectId: 'aquaapp-1564f',
    authDomain: 'aquaapp-1564f.firebaseapp.com',
    storageBucket: 'aquaapp-1564f.firebasestorage.app',
    measurementId: 'G-B0KSD05L1D',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCArfVX2JKDj1qPoKeyeiuJtGOIuBNRzi0',
    appId: '1:870482339256:android:c9d707c562a05a65f71b4d',
    messagingSenderId: '870482339256',
    projectId: 'aquaapp-1564f',
    storageBucket: 'aquaapp-1564f.firebasestorage.app',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PiTeaOcOamohYNbfdlpEp0dFjkJyi-s',
    appId: '1:870482339256:ios:a1288f10ac1983fef71b4d',
    messagingSenderId: '870482339256',
    projectId: 'aquaapp-1564f',
    storageBucket: 'aquaapp-1564f.firebasestorage.app',
    iosBundleId: 'com.example.aquaApp',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PiTeaOcOamohYNbfdlpEp0dFjkJyi-s',
    appId: '1:870482339256:ios:a1288f10ac1983fef71b4d',
    messagingSenderId: '870482339256',
    projectId: 'aquaapp-1564f',
    storageBucket: 'aquaapp-1564f.firebasestorage.app',
    iosBundleId: 'com.example.aquaApp',
    databaseURL: _databaseURL,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdexqtFzXdLMOAulMB6Lkx3OVHAoSRwF4',
    appId: '1:870482339256:web:bd04a713ad5620f1f71b4d',
    messagingSenderId: '870482339256',
    projectId: 'aquaapp-1564f',
    authDomain: 'aquaapp-1564f.firebaseapp.com',
    storageBucket: 'aquaapp-1564f.firebasestorage.app',
    measurementId: 'G-11WCSQHG1V',
    databaseURL: _databaseURL,
  );
}